title: Reflected Intelligence
description: >-

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  footnote_nr: 1
  footnotes: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore

# Custom settings
author: Evan Volgas
permalink: /:year/:month/:day/:title/
show_excerpts: true

url: "https://reflectedintelligence.com" # Replace with your actual domain
baseurl: "" # Empty if site is at the root of the domain

# Navigation
header_pages:
  - blog.md
  - about.md
